<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = [
            ['name' => 'Afrikaans', 'value' => 'af', 'is_enable' => 0],
            ['name' => 'Albanian', 'value' => 'sq', 'is_enable' => 0],
            ['name' => 'Aragonese', 'value' => 'an', 'is_enable' => 0],
            ['name' => 'Arabic (Standard)', 'value' => 'ar', 'is_enable' => 0],
            ['name' => 'Arabic (Algeria)', 'value' => 'ar-dz', 'is_enable' => 0],
            ['name' => 'Arabic (Bahrain)', 'value' => 'ar-bh', 'is_enable' => 0],
            ['name' => 'Arabic (Egypt)', 'value' => 'ar-eg', 'is_enable' => 0],
            ['name' => 'Arabic (Iraq)', 'value' => 'ar-iq', 'is_enable' => 0],
            ['name' => 'Arabic (Jordan)', 'value' => 'ar-jo', 'is_enable' => 0],
            ['name' => 'Arabic (Kuwait)', 'value' => 'ar-kw', 'is_enable' => 0],
            ['name' => 'Arabic (Lebanon)', 'value' => 'ar-lb', 'is_enable' => 0],
            ['name' => 'Arabic (Libya)', 'value' => 'ar-ly', 'is_enable' => 0],
            ['name' => 'Arabic (Morocco)', 'value' => 'ar-ma', 'is_enable' => 0],
            ['name' => 'Arabic (Oman)', 'value' => 'ar-om', 'is_enable' => 0],
            ['name' => 'Arabic (Qatar)', 'value' => 'ar-qa', 'is_enable' => 0],
            ['name' => 'Arabic (Saudi Arabia)', 'value' => 'ar-sa', 'is_enable' => 0],
            ['name' => 'Arabic (Syria)', 'value' => 'ar-sy', 'is_enable' => 0],
            ['name' => 'Arabic (Tunisia)', 'value' => 'ar-tn', 'is_enable' => 0],
            ['name' => 'Arabic (U.A.E.)', 'value' => 'ar-ae', 'is_enable' => 0],
            ['name' => 'Arabic (Yemen)', 'value' => 'ar-ye', 'is_enable' => 0],
            ['name' => 'Armenian', 'value' => 'hy', 'is_enable' => 0],
            ['name' => 'Assamese', 'value' => 'as', 'is_enable' => 0],
            ['name' => 'Asturian', 'value' => 'ast', 'is_enable' => 0],
            ['name' => 'Azerbaijani', 'value' => 'az', 'is_enable' => 0],
            ['name' => 'Basque', 'value' => 'eu', 'is_enable' => 0],
            ['name' => 'Bulgarian', 'value' => 'bg', 'is_enable' => 0],
            ['name' => 'Belarusian', 'value' => 'be', 'is_enable' => 0],
            ['name' => 'Bengali', 'value' => 'bn', 'is_enable' => 0],
            ['name' => 'Bosnian', 'value' => 'bs', 'is_enable' => 0],
            ['name' => 'Breton', 'value' => 'br', 'is_enable' => 0],
            ['name' => 'Bulgarian', 'value' => 'bg', 'is_enable' => 0],
            ['name' => 'Burmese', 'value' => 'my', 'is_enable' => 0],
            ['name' => 'Catalan', 'value' => 'ca', 'is_enable' => 0],
            ['name' => 'Chamorro', 'value' => 'ch', 'is_enable' => 0],
            ['name' => 'Chechen', 'value' => 'ce', 'is_enable' => 0],
            ['name' => 'Chinese', 'value' => 'zh', 'is_enable' => 0],
            ['name' => 'Chinese (Hong Kong)', 'value' => 'zh-hk', 'is_enable' => 0],
            ['name' => 'Chinese (PRC)', 'value' => 'zh-cn', 'is_enable' => 0],
            ['name' => 'Chinese (Singapore)', 'value' => '"zh-sg', 'is_enable' => 0],
            ['name' => 'Chinese (Taiwan)', 'value' => 'zh-tw', 'is_enable' => 0],
            ['name' => 'Chuvash', 'value' => 'cv', 'is_enable' => 0],
            ['name' => 'Corsican', 'value' => 'co', 'is_enable' => 0],
            ['name' => 'Cree', 'value' => 'cr', 'is_enable' => 0],
            ['name' => 'Croatian', 'value' => 'hr', 'is_enable' => 0],
            ['name' => 'Czech', 'value' => 'cs', 'is_enable' => 0],
            ['name' => 'Danish', 'value' => 'da', 'is_enable' => 0],
            ['name' => 'Dutch (Standard)', 'value' => 'nl', 'is_enable' => 0],
            ['name' => 'Dutch (Belgian)', 'value' => 'nl-be', 'is_enable' => 0],
            ['name' => 'English', 'value' => 'en', 'is_enable' => 0],
            ['name' => 'English (Australia)', 'value' => 'en-au', 'is_enable' => 0],
            ['name' => 'English (Belize)', 'value' => 'en-bz', 'is_enable' => 0],
            ['name' => 'English (Canada)', 'value' => 'en-ca', 'is_enable' => 0],
            ['name' => 'English (Ireland)', 'value' => 'en-ie', 'is_enable' => 0],
            ['name' => 'English (Jamaica)', 'value' => 'en-jm', 'is_enable' => 0],
            ['name' => 'English (New Zealand)', 'value' => 'en-nz', 'is_enable' => 0],
            ['name' => 'English (Philippines)', 'value' => 'en-ph', 'is_enable' => 0],
            ['name' => 'English (South Africa)', 'value' => 'en-za', 'is_enable' => 0],
            ['name' => 'English (Trinidad & Tobago)', 'value' => 'en-tt', 'is_enable' => 0],
            ['name' => 'English (United Kingdom)', 'value' => 'en-gb', 'is_enable' => 0],
            ['name' => 'English (United States)', 'value' => 'en-us', 'is_enable' => 0],
            ['name' => 'English (Zimbabwe)', 'value' => 'en-zw', 'is_enable' => 0],
            ['name' => 'Esperanto', 'value' => 'eo', 'is_enable' => 0],
            ['name' => 'Estonian', 'value' => 'et', 'is_enable' => 0],
            ['name' => 'Faeroese', 'value' => 'fo', 'is_enable' => 0],
            ['name' => 'Farsi', 'value' => 'fa', 'is_enable' => 0],
            ['name' => 'Fijian', 'value' => 'fj', 'is_enable' => 0],
            ['name' => 'Finnish', 'value' => 'fi', 'is_enable' => 0],
            ['name' => 'French (Standard)', 'value' => 'fr', 'is_enable' => 0],
            ['name' => 'French (Belgium)', 'value' => 'fr-be', 'is_enable' => 0],
            ['name' => 'French (Canada)', 'value' => 'fr-ca', 'is_enable' => 0],
            ['name' => 'French (France)', 'value' => 'fr-fr', 'is_enable' => 0],
            ['name' => 'French (Luxembourg)', 'value' => 'fr-lu', 'is_enable' => 0],
            ['name' => 'French (Monaco)', 'value' => 'fr-mc', 'is_enable' => 0],
            ['name' => 'French (Switzerland)', 'value' => 'fr-ch', 'is_enable' => 0],
            ['name' => 'Frisian', 'value' => 'fy', 'is_enable' => 0],
            ['name' => 'Friulian', 'value' => 'fur', 'is_enable' => 0],
            ['name' => 'Gaelic (Scots)', 'value' => 'gd', 'is_enable' => 0],
            ['name' => 'Gaelic (Irish)', 'value' => 'gd-ie', 'is_enable' => 0],
            ['name' => 'Galacian', 'value' => 'gl', 'is_enable' => 0],
            ['name' => 'Georgian', 'value' => 'ka', 'is_enable' => 0],
            ['name' => 'German (Standard)', 'value' => 'de', 'is_enable' => 0],
            ['name' => 'German (Austria)', 'value' => 'de-at', 'is_enable' => 0],
            ['name' => 'German (Germany)', 'value' => 'de-de', 'is_enable' => 0],
            ['name' => 'German (Liechtenstein)', 'value' => 'de-li', 'is_enable' => 0],
            ['name' => 'German (Luxembourg)', 'value' => 'de-lu', 'is_enable' => 0],
            ['name' => 'German (Switzerland)', 'value' => 'de-ch', 'is_enable' => 0],
            ['name' => 'Greek', 'value' => 'el', 'is_enable' => 0],
            ['name' => 'Gujurati', 'value' => 'gu', 'is_enable' => 0],
            ['name' => 'Haitian', 'value' => 'ht', 'is_enable' => 0],
            ['name' => 'Hebrew', 'value' => 'he', 'is_enable' => 0],
            ['name' => 'Hindi', 'value' => 'hi', 'is_enable' => 0],
            ['name' => 'Hungarian', 'value' => 'hu', 'is_enable' => 0],
            ['name' => 'Icelandic', 'value' => 'is', 'is_enable' => 0],
            ['name' => 'Indonesian', 'value' => 'id', 'is_enable' => 0],
            ['name' => 'Inuktitut', 'value' => 'iu', 'is_enable' => 0],
            ['name' => 'Irish', 'value' => 'ga', 'is_enable' => 0],
            ['name' => 'Italian (Standard)', 'value' => 'it', 'is_enable' => 0],
            ['name' => 'Italian (Switzerland)', 'value' => 'it-ch', 'is_enable' => 0],
            ['name' => 'Japanese', 'value' => 'ja', 'is_enable' => 0],
            ['name' => 'Kannada', 'value' => 'kn', 'is_enable' => 0],
            ['name' => 'Kashmiri', 'value' => 'ks', 'is_enable' => 0],
            ['name' => 'Kazakh', 'value' => 'kk', 'is_enable' => 0],
            ['name' => 'Khmer', 'value' => 'km', 'is_enable' => 0],
            ['name' => 'Kirghiz', 'value' => 'ky', 'is_enable' => 0],
            ['name' => 'Klingon', 'value' => 'tlh', 'is_enable' => 0],
            ['name' => 'Korean', 'value' => 'ko', 'is_enable' => 0],
            ['name' => 'Korean (North Korea)', 'value' => 'ko-kp', 'is_enable' => 0],
            ['name' => 'Korean (South Korea)', 'value' => 'ko-kr', 'is_enable' => 0],
            ['name' => 'Latin', 'value' => 'la', 'is_enable' => 0],
            ['name' => 'Latvian', 'value' => 'lv', 'is_enable' => 0],
            ['name' => 'Lithuanian', 'value' => 'lt', 'is_enable' => 0],
            ['name' => 'Luxembourgish', 'value' => 'lb', 'is_enable' => 0],
            ['name' => 'FYRO Macedonian', 'value' => 'mk', 'is_enable' => 0],
            ['name' => 'Malay', 'value' => 'ms', 'is_enable' => 0],
            ['name' => 'Malayalam', 'value' => 'ml', 'is_enable' => 0],
            ['name' => 'Maltese', 'value' => 'mt', 'is_enable' => 0],
            ['name' => 'Maori', 'value' => 'mi', 'is_enable' => 0],
            ['name' => 'Marathi', 'value' => 'mr', 'is_enable' => 0],
            ['name' => 'Moldavian', 'value' => 'mo', 'is_enable' => 0],
            ['name' => 'Navajo', 'value' => 'nv', 'is_enable' => 0],
            ['name' => 'Ndonga', 'value' => 'ng', 'is_enable' => 0],
            ['name' => 'Nepali', 'value' => 'ne', 'is_enable' => 0],
            ['name' => 'Norwegian', 'value' => 'no', 'is_enable' => 0],
            ['name' => 'Norwegian (Bokmal)', 'value' => 'nb', 'is_enable' => 0],
            ['name' => 'Norwegian (Nynorsk)', 'value' => 'nn', 'is_enable' => 0],
            ['name' => 'Occitan', 'value' => 'oc', 'is_enable' => 0],
            ['name' => 'Oriya', 'value' => 'or', 'is_enable' => 0],
            ['name' => 'Oromo', 'value' => 'om', 'is_enable' => 0],
            ['name' => 'Persian', 'value' => 'fa', 'is_enable' => 0],
            ['name' => 'Persian/Iran', 'value' => 'fa-ir', 'is_enable' => 0],
            ['name' => 'Polish', 'value' => 'pl', 'is_enable' => 0],
            ['name' => 'Portuguese', 'value' => 'pt', 'is_enable' => 0],
            ['name' => 'Portuguese (Brazil)', 'value' => 'pt-br', 'is_enable' => 0],
            ['name' => 'Punjabi', 'value' => 'pa', 'is_enable' => 0],
            ['name' => 'Punjabi (India)', 'value' => 'pa-in', 'is_enable' => 0],
            ['name' => 'Punjabi (Pakistan)', 'value' => 'pa-pk', 'is_enable' => 0],
            ['name' => 'Quechua', 'value' => 'qu', 'is_enable' => 0],
            ['name' => 'Rhaeto-Romanic', 'value' => 'rm', 'is_enable' => 0],
            ['name' => 'Romanian', 'value' => 'ro', 'is_enable' => 0],
            ['name' => 'Romanian (Moldavia)', 'value' => 'ro-mo', 'is_enable' => 0],
            ['name' => 'Russian', 'value' => 'ru', 'is_enable' => 0],
            ['name' => 'Russian (Moldavia)', 'value' => 'ru-mo', 'is_enable' => 0],
            ['name' => 'Sami (Lappish)', 'value' => 'sz', 'is_enable' => 0],
            ['name' => 'Sango', 'value' => 'sg', 'is_enable' => 0],
            ['name' => 'Sanskrit', 'value' => 'sa', 'is_enable' => 0],
            ['name' => 'Sardinian', 'value' => 'sc', 'is_enable' => 0],
            ['name' => 'Scots Gaelic', 'value' => 'gd', 'is_enable' => 0],
            ['name' => 'Sindhi', 'value' => 'sd', 'is_enable' => 0],
            ['name' => 'Singhalese', 'value' => 'si', 'is_enable' => 0],
            ['name' => 'Serbian', 'value' => 'sr', 'is_enable' => 0],
            ['name' => 'Slovak', 'value' => 'sk', 'is_enable' => 0],
            ['name' => 'Slovenian', 'value' => 'sl', 'is_enable' => 0],
            ['name' => 'Somani', 'value' => 'so', 'is_enable' => 0],
            ['name' => 'Sorbian', 'value' => 'sb', 'is_enable' => 0],
            ['name' => 'Spanish', 'value' => 'es', 'is_enable' => 0],
            ['name' => 'Spanish (Argentina)', 'value' => 'es-ar', 'is_enable' => 0],
            ['name' => 'Spanish (Bolivia)', 'value' => 'es-bo', 'is_enable' => 0],
            ['name' => 'Spanish (Chile)', 'value' => 'es-cl', 'is_enable' => 0],
            ['name' => 'Spanish (Colombia)', 'value' => 'es-co', 'is_enable' => 0],
            ['name' => 'Spanish (Costa Rica)', 'value' => 'es-cr', 'is_enable' => 0],
            ['name' => 'Spanish (Dominican Republic)', 'value' => 'es-do', 'is_enable' => 0],
            ['name' => 'Spanish (Ecuador)', 'value' => 'es-ec', 'is_enable' => 0],
            ['name' => 'Spanish (El Salvador)', 'value' => 'es-sv', 'is_enable' => 0],
            ['name' => 'Spanish (Guatemala)', 'value' => 'es-gt', 'is_enable' => 0],
            ['name' => 'Spanish (Honduras)', 'value' => 'es-hn', 'is_enable' => 0],
            ['name' => 'Spanish (Mexico)', 'value' => 'es-mx', 'is_enable' => 0],
            ['name' => 'Spanish (Nicaragua)', 'value' => 'es-ni', 'is_enable' => 0],
            ['name' => 'Spanish (Panama)', 'value' => 'es-pa', 'is_enable' => 0],
            ['name' => 'Spanish (Paraguay)', 'value' => 'es-py', 'is_enable' => 0],
            ['name' => 'Spanish (Peru)', 'value' => 'es-pe', 'is_enable' => 0],
            ['name' => 'Spanish (Puerto Rico)', 'value' => 'es-pr', 'is_enable' => 0],
            ['name' => 'Spanish (Spain)', 'value' => 'es-es', 'is_enable' => 0],
            ['name' => 'Spanish (Uruguay)', 'value' => 'es-uy', 'is_enable' => 0],
            ['name' => 'Spanish (Venezuela)', 'value' => 'es-ve', 'is_enable' => 0],
            ['name' => 'Sutu', 'value' => 'sx', 'is_enable' => 0],
            ['name' => 'Swahili', 'value' => 'sw', 'is_enable' => 0],
            ['name' => 'Swedish', 'value' => 'sv', 'is_enable' => 0],
            ['name' => 'Swedish (Finland)', 'value' => 'sv-fi', 'is_enable' => 0],
            ['name' => 'Swedish (Sweden)', 'value' => 'sv-sv', 'is_enable' => 0],
            ['name' => 'Tamil', 'value' => 'ta', 'is_enable' => 0],
            ['name' => 'Tatar', 'value' => 'tt', 'is_enable' => 0],
            ['name' => 'Teluga', 'value' => 'te', 'is_enable' => 0],
            ['name' => 'Thai', 'value' => 'th', 'is_enable' => 0],
            ['name' => 'Tigre', 'value' => 'tig', 'is_enable' => 0],
            ['name' => 'Tsonga', 'value' => 'ts', 'is_enable' => 0],
            ['name' => 'Tswana', 'value' => 'tn', 'is_enable' => 0],
            ['name' => 'Turkish', 'value' => 'tr', 'is_enable' => 0],
            ['name' => 'Turkmen', 'value' => 'tk', 'is_enable' => 0],
            ['name' => 'Ukrainian', 'value' => 'uk', 'is_enable' => 0],
            ['name' => 'Upper Sorbian', 'value' => 'hsb', 'is_enable' => 0],
            ['name' => 'Urdu', 'value' => 'ur', 'is_enable' => 0],
            ['name' => 'Venda', 'value' => 've', 'is_enable' => 0],
            ['name' => 'Vietnamese', 'value' => 'vi', 'is_enable' => 0],
            ['name' => 'Volapuk', 'value' => 'vo', 'is_enable' => 0],
            ['name' => 'Walloon', 'value' => 'wa', 'is_enable' => 0],
            ['name' => 'Welsh', 'value' => 'cy', 'is_enable' => 0],
            ['name' => 'Xhosa', 'value' => 'xh', 'is_enable' => 0],
            ['name' => 'Yiddish', 'value' => 'ji', 'is_enable' => 0],
            ['name' => 'Zulu', 'value' => 'zu', 'is_enable' => 0],
        ];

        foreach ($languages as $language) {
            Language::create($language);
        }
    }
}
